name: macos

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: install Go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.15.6'

    - name: Run test
      run: go test -v ./...
